### ISSUE TITLE
Create Main Activity with a simple button

### ISSUE THREAD

**Issue by aviaryan** [saurabhjn76/WikipediaTextSearch#5]

**Comment by dougouk** [comment]
What should the button do?

**Comment by dougouk** [comment]
Added pull request https://github.com/saurabhjn76/WikipediaTextSearch/pull/7 lol

**Comment by till-tomorrow** [comment]
button for doing what?

**Comment by LeoColman** [comment]
This is an attempt to get credits at Hacktoberfest. Report it as spam!

**Comment by dougouk** [comment]
haha I thought so, oh well

**Comment by LeoColman** [comment]
Should mark it as Invalid
